osx_image: xcode10
language: objective-c

before_install:
  - pod install

script:
  - set -o pipefail && xcodebuild -workspace Gray.xcworkspace -scheme "Gray" -sdk macosx clean build | xcpretty

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
